server:
  port: 81
spring:
  rabbitmq:
    host: 47.112.181.157
    port: 5672
    username: admin
    password: admin
    virtual-host: /
      #开启手动Ack
#    listener:
#      simple:
#        #自动应答
#        acknowledge-mode: auto
#        retry:
#          #是否重试
#          enabled: true
#          #重试间隔
#          initial-interval: 2000ms
#          #最多重试多少次
#          max-attempts: 3



  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?characterEncoding=UTF8
    username: root
    password: 1998
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall,log4j2
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: false
  type-aliases-package: com.ex.entity
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
