server:
  port: 81

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.55.6.73:3306/test?characterEncoding=UTF8&useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1998
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始连接数
      initial-size: 10
      #最大连接数
      max-active: 100
      #最小连接数0
      min-idle: 10
      #获取连接等待超时的时间 ms
      max-wait: 60000

#mybatis映射配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
  type-aliases-package: com.ex.entity
