spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/base?characterEncoding=UTF8
      username: root
      password: 1998

mybatis:
  type-aliases-package: com.ex.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    local-cache-scope: statement
    cache-enabled: false
