server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base?characterEncoding=UTF8
    username: root
    password: 1998
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info

mybatis-plus:
  #mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: false
  type-aliases-package: com.ex.entity
